# Generated by Django 3.2.16 on 2025-01-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
